// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: gridkv_gossip.proto

package gossip

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NodeState defines the health status of a node.
type NodeState int32

const (
	NodeState_NODE_STATE_UNKNOWN NodeState = 0
	NodeState_NODE_STATE_ALIVE   NodeState = 1
	NodeState_NODE_STATE_SUSPECT NodeState = 2
	NodeState_NODE_STATE_DEAD    NodeState = 3
)

// Enum value maps for NodeState.
var (
	NodeState_name = map[int32]string{
		0: "NODE_STATE_UNKNOWN",
		1: "NODE_STATE_ALIVE",
		2: "NODE_STATE_SUSPECT",
		3: "NODE_STATE_DEAD",
	}
	NodeState_value = map[string]int32{
		"NODE_STATE_UNKNOWN": 0,
		"NODE_STATE_ALIVE":   1,
		"NODE_STATE_SUSPECT": 2,
		"NODE_STATE_DEAD":    3,
	}
)

func (x NodeState) Enum() *NodeState {
	p := new(NodeState)
	*p = x
	return p
}

func (x NodeState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeState) Descriptor() protoreflect.EnumDescriptor {
	return file_gridkv_gossip_proto_enumTypes[0].Descriptor()
}

func (NodeState) Type() protoreflect.EnumType {
	return &file_gridkv_gossip_proto_enumTypes[0]
}

func (x NodeState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeState.Descriptor instead.
func (NodeState) EnumDescriptor() ([]byte, []int) {
	return file_gridkv_gossip_proto_rawDescGZIP(), []int{0}
}

// GossipMessageType defines the type of message being transmitted.
type GossipMessageType int32

const (
	GossipMessageType_MESSAGE_TYPE_UNKNOWN        GossipMessageType = 0
	GossipMessageType_MESSAGE_TYPE_CACHE_SYNC     GossipMessageType = 1
	GossipMessageType_MESSAGE_TYPE_CLUSTER_SYNC   GossipMessageType = 2
	GossipMessageType_MESSAGE_TYPE_CONNECT        GossipMessageType = 3
	GossipMessageType_MESSAGE_TYPE_PROBE_REQUEST  GossipMessageType = 4
	GossipMessageType_MESSAGE_TYPE_PROBE_RESPONSE GossipMessageType = 5
	// New/added types for ACKs and full-sync control:
	GossipMessageType_MESSAGE_TYPE_CACHE_SYNC_ACK     GossipMessageType = 6
	GossipMessageType_MESSAGE_TYPE_FULL_SYNC_REQUEST  GossipMessageType = 7
	GossipMessageType_MESSAGE_TYPE_FULL_SYNC_RESPONSE GossipMessageType = 8
	// Read operations with quorum support:
	GossipMessageType_MESSAGE_TYPE_READ_REQUEST  GossipMessageType = 9
	GossipMessageType_MESSAGE_TYPE_READ_RESPONSE GossipMessageType = 10
)

// Enum value maps for GossipMessageType.
var (
	GossipMessageType_name = map[int32]string{
		0:  "MESSAGE_TYPE_UNKNOWN",
		1:  "MESSAGE_TYPE_CACHE_SYNC",
		2:  "MESSAGE_TYPE_CLUSTER_SYNC",
		3:  "MESSAGE_TYPE_CONNECT",
		4:  "MESSAGE_TYPE_PROBE_REQUEST",
		5:  "MESSAGE_TYPE_PROBE_RESPONSE",
		6:  "MESSAGE_TYPE_CACHE_SYNC_ACK",
		7:  "MESSAGE_TYPE_FULL_SYNC_REQUEST",
		8:  "MESSAGE_TYPE_FULL_SYNC_RESPONSE",
		9:  "MESSAGE_TYPE_READ_REQUEST",
		10: "MESSAGE_TYPE_READ_RESPONSE",
	}
	GossipMessageType_value = map[string]int32{
		"MESSAGE_TYPE_UNKNOWN":            0,
		"MESSAGE_TYPE_CACHE_SYNC":         1,
		"MESSAGE_TYPE_CLUSTER_SYNC":       2,
		"MESSAGE_TYPE_CONNECT":            3,
		"MESSAGE_TYPE_PROBE_REQUEST":      4,
		"MESSAGE_TYPE_PROBE_RESPONSE":     5,
		"MESSAGE_TYPE_CACHE_SYNC_ACK":     6,
		"MESSAGE_TYPE_FULL_SYNC_REQUEST":  7,
		"MESSAGE_TYPE_FULL_SYNC_RESPONSE": 8,
		"MESSAGE_TYPE_READ_REQUEST":       9,
		"MESSAGE_TYPE_READ_RESPONSE":      10,
	}
)

func (x GossipMessageType) Enum() *GossipMessageType {
	p := new(GossipMessageType)
	*p = x
	return p
}

func (x GossipMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GossipMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_gridkv_gossip_proto_enumTypes[1].Descriptor()
}

func (GossipMessageType) Type() protoreflect.EnumType {
	return &file_gridkv_gossip_proto_enumTypes[1]
}

func (x GossipMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GossipMessageType.Descriptor instead.
func (GossipMessageType) EnumDescriptor() ([]byte, []int) {
	return file_gridkv_gossip_proto_rawDescGZIP(), []int{1}
}

// OperationType specifies the explicit action being performed on a cache item.
type OperationType int32

const (
	OperationType_OP_UNSPECIFIED OperationType = 0
	OperationType_OP_SET         OperationType = 1
	OperationType_OP_DELETE      OperationType = 2
)

// Enum value maps for OperationType.
var (
	OperationType_name = map[int32]string{
		0: "OP_UNSPECIFIED",
		1: "OP_SET",
		2: "OP_DELETE",
	}
	OperationType_value = map[string]int32{
		"OP_UNSPECIFIED": 0,
		"OP_SET":         1,
		"OP_DELETE":      2,
	}
)

func (x OperationType) Enum() *OperationType {
	p := new(OperationType)
	*p = x
	return p
}

func (x OperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_gridkv_gossip_proto_enumTypes[2].Descriptor()
}

func (OperationType) Type() protoreflect.EnumType {
	return &file_gridkv_gossip_proto_enumTypes[2]
}

func (x OperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationType.Descriptor instead.
func (OperationType) EnumDescriptor() ([]byte, []int) {
	return file_gridkv_gossip_proto_rawDescGZIP(), []int{2}
}

// NodeInfo represents metadata for a single cluster member.
type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	LastActiveTs  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_active_ts,json=lastActiveTs,proto3" json:"last_active_ts,omitempty"`
	State         NodeState              `protobuf:"varint,4,opt,name=state,proto3,enum=gossip.NodeState" json:"state,omitempty"`
	Version       int64                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_gridkv_gossip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_gridkv_gossip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_gridkv_gossip_proto_rawDescGZIP(), []int{0}
}

func (x *NodeInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NodeInfo) GetLastActiveTs() *timestamppb.Timestamp {
	if x != nil {
		return x.LastActiveTs
	}
	return nil
}

func (x *NodeInfo) GetState() NodeState {
	if x != nil {
		return x.State
	}
	return NodeState_NODE_STATE_UNKNOWN
}

func (x *NodeInfo) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

// ConnectPayload is sent when a new node joins the cluster.
type ConnectPayload struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	NodeId  string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Version int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	// Optional HLC timestamp string (format: node:unixnano:counter)
	Hlc string `protobuf:"bytes,4,opt,name=hlc,proto3" json:"hlc,omitempty"`
	// Public key for message signature verification (Ed25519)
	PublicKey     []byte `protobuf:"bytes,5,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectPayload) Reset() {
	*x = ConnectPayload{}
	mi := &file_gridkv_gossip_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectPayload) ProtoMessage() {}

func (x *ConnectPayload) ProtoReflect() protoreflect.Message {
	mi := &file_gridkv_gossip_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectPayload.ProtoReflect.Descriptor instead.
func (*ConnectPayload) Descriptor() ([]byte, []int) {
	return file_gridkv_gossip_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectPayload) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ConnectPayload) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ConnectPayload) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ConnectPayload) GetHlc() string {
	if x != nil {
		return x.Hlc
	}
	return ""
}

func (x *ConnectPayload) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

// ClusterSyncPayload contains a list of known nodes for state synchronization.
type ClusterSyncPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeInfo            `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterSyncPayload) Reset() {
	*x = ClusterSyncPayload{}
	mi := &file_gridkv_gossip_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterSyncPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterSyncPayload) ProtoMessage() {}

func (x *ClusterSyncPayload) ProtoReflect() protoreflect.Message {
	mi := &file_gridkv_gossip_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterSyncPayload.ProtoReflect.Descriptor instead.
func (*ClusterSyncPayload) Descriptor() ([]byte, []int) {
	return file_gridkv_gossip_proto_rawDescGZIP(), []int{2}
}

func (x *ClusterSyncPayload) GetNodes() []*NodeInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

// ProbePayload is used for indirect failure detection.
type ProbePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetNodeId  string                 `protobuf:"bytes,1,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`
	RequesterId   string                 `protobuf:"bytes,2,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbePayload) Reset() {
	*x = ProbePayload{}
	mi := &file_gridkv_gossip_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbePayload) ProtoMessage() {}

func (x *ProbePayload) ProtoReflect() protoreflect.Message {
	mi := &file_gridkv_gossip_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbePayload.ProtoReflect.Descriptor instead.
func (*ProbePayload) Descriptor() ([]byte, []int) {
	return file_gridkv_gossip_proto_rawDescGZIP(), []int{3}
}

func (x *ProbePayload) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

func (x *ProbePayload) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

// ProbeResponsePayload is the response to an indirect probe.
type ProbeResponsePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetNodeId  string                 `protobuf:"bytes,1,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`
	Alive         bool                   `protobuf:"varint,2,opt,name=alive,proto3" json:"alive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeResponsePayload) Reset() {
	*x = ProbeResponsePayload{}
	mi := &file_gridkv_gossip_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeResponsePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeResponsePayload) ProtoMessage() {}

func (x *ProbeResponsePayload) ProtoReflect() protoreflect.Message {
	mi := &file_gridkv_gossip_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeResponsePayload.ProtoReflect.Descriptor instead.
func (*ProbeResponsePayload) Descriptor() ([]byte, []int) {
	return file_gridkv_gossip_proto_rawDescGZIP(), []int{4}
}

func (x *ProbeResponsePayload) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

func (x *ProbeResponsePayload) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

// StoredItem contains the actual data being stored for SET/UPDATE operations.
type StoredItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpireAt      uint64                 `protobuf:"fixed64,1,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoredItem) Reset() {
	*x = StoredItem{}
	mi := &file_gridkv_gossip_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoredItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoredItem) ProtoMessage() {}

func (x *StoredItem) ProtoReflect() protoreflect.Message {
	mi := &file_gridkv_gossip_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoredItem.ProtoReflect.Descriptor instead.
func (*StoredItem) Descriptor() ([]byte, []int) {
	return file_gridkv_gossip_proto_rawDescGZIP(), []int{5}
}

func (x *StoredItem) GetExpireAt() uint64 {
	if x != nil {
		return x.ExpireAt
	}
	return 0
}

func (x *StoredItem) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// CacheSyncOperation defines a single, atomic change to a cache item (the delta).
type CacheSyncOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ClientVersion int64                  `protobuf:"varint,2,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	Type          OperationType          `protobuf:"varint,3,opt,name=type,proto3,enum=gossip.OperationType" json:"type,omitempty"`
	// Types that are valid to be assigned to DataPayload:
	//
	//	*CacheSyncOperation_SetData
	DataPayload   isCacheSyncOperation_DataPayload `protobuf_oneof:"data_payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheSyncOperation) Reset() {
	*x = CacheSyncOperation{}
	mi := &file_gridkv_gossip_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheSyncOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheSyncOperation) ProtoMessage() {}

func (x *CacheSyncOperation) ProtoReflect() protoreflect.Message {
	mi := &file_gridkv_gossip_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheSyncOperation.ProtoReflect.Descriptor instead.
func (*CacheSyncOperation) Descriptor() ([]byte, []int) {
	return file_gridkv_gossip_proto_rawDescGZIP(), []int{6}
}

func (x *CacheSyncOperation) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CacheSyncOperation) GetClientVersion() int64 {
	if x != nil {
		return x.ClientVersion
	}
	return 0
}

func (x *CacheSyncOperation) GetType() OperationType {
	if x != nil {
		return x.Type
	}
	return OperationType_OP_UNSPECIFIED
}

func (x *CacheSyncOperation) GetDataPayload() isCacheSyncOperation_DataPayload {
	if x != nil {
		return x.DataPayload
	}
	return nil
}

func (x *CacheSyncOperation) GetSetData() *StoredItem {
	if x != nil {
		if x, ok := x.DataPayload.(*CacheSyncOperation_SetData); ok {
			return x.SetData
		}
	}
	return nil
}

type isCacheSyncOperation_DataPayload interface {
	isCacheSyncOperation_DataPayload()
}

type CacheSyncOperation_SetData struct {
	SetData *StoredItem `protobuf:"bytes,4,opt,name=set_data,json=setData,proto3,oneof"`
}

func (*CacheSyncOperation_SetData) isCacheSyncOperation_DataPayload() {}

// IncrementalSyncPayload defines the structure for DELTA updates.
type IncrementalSyncPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operations    []*CacheSyncOperation  `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty"`
	PayloadId     string                 `protobuf:"bytes,2,opt,name=payload_id,json=payloadId,proto3" json:"payload_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrementalSyncPayload) Reset() {
	*x = IncrementalSyncPayload{}
	mi := &file_gridkv_gossip_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementalSyncPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementalSyncPayload) ProtoMessage() {}

func (x *IncrementalSyncPayload) ProtoReflect() protoreflect.Message {
	mi := &file_gridkv_gossip_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementalSyncPayload.ProtoReflect.Descriptor instead.
func (*IncrementalSyncPayload) Descriptor() ([]byte, []int) {
	return file_gridkv_gossip_proto_rawDescGZIP(), []int{7}
}

func (x *IncrementalSyncPayload) GetOperations() []*CacheSyncOperation {
	if x != nil {
		return x.Operations
	}
	return nil
}

func (x *IncrementalSyncPayload) GetPayloadId() string {
	if x != nil {
		return x.PayloadId
	}
	return ""
}

// FullStateItem represents a complete key-value entry for the Full Sync mode.
type FullStateItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	ItemData      *StoredItem            `protobuf:"bytes,3,opt,name=item_data,json=itemData,proto3" json:"item_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FullStateItem) Reset() {
	*x = FullStateItem{}
	mi := &file_gridkv_gossip_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullStateItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullStateItem) ProtoMessage() {}

func (x *FullStateItem) ProtoReflect() protoreflect.Message {
	mi := &file_gridkv_gossip_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullStateItem.ProtoReflect.Descriptor instead.
func (*FullStateItem) Descriptor() ([]byte, []int) {
	return file_gridkv_gossip_proto_rawDescGZIP(), []int{8}
}

func (x *FullStateItem) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *FullStateItem) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *FullStateItem) GetItemData() *StoredItem {
	if x != nil {
		return x.ItemData
	}
	return nil
}

// FullSyncPayload defines the structure for a COMPLETE state snapshot.
type FullSyncPayload struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Items             []*FullStateItem       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	SnapshotTimestamp uint64                 `protobuf:"fixed64,2,opt,name=snapshot_timestamp,json=snapshotTimestamp,proto3" json:"snapshot_timestamp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FullSyncPayload) Reset() {
	*x = FullSyncPayload{}
	mi := &file_gridkv_gossip_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullSyncPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullSyncPayload) ProtoMessage() {}

func (x *FullSyncPayload) ProtoReflect() protoreflect.Message {
	mi := &file_gridkv_gossip_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullSyncPayload.ProtoReflect.Descriptor instead.
func (*FullSyncPayload) Descriptor() ([]byte, []int) {
	return file_gridkv_gossip_proto_rawDescGZIP(), []int{9}
}

func (x *FullSyncPayload) GetItems() []*FullStateItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *FullSyncPayload) GetSnapshotTimestamp() uint64 {
	if x != nil {
		return x.SnapshotTimestamp
	}
	return 0
}

// SyncMessage is the top-level wrapper for all CACHE synchronization data.
type SyncMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to SyncType:
	//
	//	*SyncMessage_IncrementalSync
	//	*SyncMessage_FullSync
	SyncType      isSyncMessage_SyncType `protobuf_oneof:"sync_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncMessage) Reset() {
	*x = SyncMessage{}
	mi := &file_gridkv_gossip_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncMessage) ProtoMessage() {}

func (x *SyncMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gridkv_gossip_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncMessage.ProtoReflect.Descriptor instead.
func (*SyncMessage) Descriptor() ([]byte, []int) {
	return file_gridkv_gossip_proto_rawDescGZIP(), []int{10}
}

func (x *SyncMessage) GetSyncType() isSyncMessage_SyncType {
	if x != nil {
		return x.SyncType
	}
	return nil
}

func (x *SyncMessage) GetIncrementalSync() *IncrementalSyncPayload {
	if x != nil {
		if x, ok := x.SyncType.(*SyncMessage_IncrementalSync); ok {
			return x.IncrementalSync
		}
	}
	return nil
}

func (x *SyncMessage) GetFullSync() *FullSyncPayload {
	if x != nil {
		if x, ok := x.SyncType.(*SyncMessage_FullSync); ok {
			return x.FullSync
		}
	}
	return nil
}

type isSyncMessage_SyncType interface {
	isSyncMessage_SyncType()
}

type SyncMessage_IncrementalSync struct {
	IncrementalSync *IncrementalSyncPayload `protobuf:"bytes,1,opt,name=incremental_sync,json=incrementalSync,proto3,oneof"`
}

type SyncMessage_FullSync struct {
	FullSync *FullSyncPayload `protobuf:"bytes,2,opt,name=full_sync,json=fullSync,proto3,oneof"`
}

func (*SyncMessage_IncrementalSync) isSyncMessage_SyncType() {}

func (*SyncMessage_FullSync) isSyncMessage_SyncType() {}

// CacheSyncAckPayload is sent by a replica to acknowledge a replication OpId.
type CacheSyncAckPayload struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	OpId   string                 `protobuf:"bytes,1,opt,name=op_id,json=opId,proto3" json:"op_id,omitempty"`
	PeerId string                 `protobuf:"bytes,2,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	// optional: success flag (true if apply succeeded)
	Success       bool `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CacheSyncAckPayload) Reset() {
	*x = CacheSyncAckPayload{}
	mi := &file_gridkv_gossip_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CacheSyncAckPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CacheSyncAckPayload) ProtoMessage() {}

func (x *CacheSyncAckPayload) ProtoReflect() protoreflect.Message {
	mi := &file_gridkv_gossip_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CacheSyncAckPayload.ProtoReflect.Descriptor instead.
func (*CacheSyncAckPayload) Descriptor() ([]byte, []int) {
	return file_gridkv_gossip_proto_rawDescGZIP(), []int{11}
}

func (x *CacheSyncAckPayload) GetOpId() string {
	if x != nil {
		return x.OpId
	}
	return ""
}

func (x *CacheSyncAckPayload) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *CacheSyncAckPayload) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// FullSyncRequestPayload is used to request a full state snapshot from a peer.
type FullSyncRequestPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequesterId   string                 `protobuf:"bytes,1,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FullSyncRequestPayload) Reset() {
	*x = FullSyncRequestPayload{}
	mi := &file_gridkv_gossip_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullSyncRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullSyncRequestPayload) ProtoMessage() {}

func (x *FullSyncRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_gridkv_gossip_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullSyncRequestPayload.ProtoReflect.Descriptor instead.
func (*FullSyncRequestPayload) Descriptor() ([]byte, []int) {
	return file_gridkv_gossip_proto_rawDescGZIP(), []int{12}
}

func (x *FullSyncRequestPayload) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

// FullSyncResponsePayload carries the complete snapshot as a response.
type FullSyncResponsePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullSync      *FullSyncPayload       `protobuf:"bytes,1,opt,name=full_sync,json=fullSync,proto3" json:"full_sync,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FullSyncResponsePayload) Reset() {
	*x = FullSyncResponsePayload{}
	mi := &file_gridkv_gossip_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullSyncResponsePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullSyncResponsePayload) ProtoMessage() {}

func (x *FullSyncResponsePayload) ProtoReflect() protoreflect.Message {
	mi := &file_gridkv_gossip_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullSyncResponsePayload.ProtoReflect.Descriptor instead.
func (*FullSyncResponsePayload) Descriptor() ([]byte, []int) {
	return file_gridkv_gossip_proto_rawDescGZIP(), []int{13}
}

func (x *FullSyncResponsePayload) GetFullSync() *FullSyncPayload {
	if x != nil {
		return x.FullSync
	}
	return nil
}

// ReadRequestPayload is used to request a value for a specific key.
type ReadRequestPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	RequesterId   string                 `protobuf:"bytes,2,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // Unique ID for correlating request/response
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequestPayload) Reset() {
	*x = ReadRequestPayload{}
	mi := &file_gridkv_gossip_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequestPayload) ProtoMessage() {}

func (x *ReadRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_gridkv_gossip_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequestPayload.ProtoReflect.Descriptor instead.
func (*ReadRequestPayload) Descriptor() ([]byte, []int) {
	return file_gridkv_gossip_proto_rawDescGZIP(), []int{14}
}

func (x *ReadRequestPayload) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ReadRequestPayload) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

func (x *ReadRequestPayload) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// ReadResponsePayload carries the value and metadata for a read request.
type ReadResponsePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // Matches the request_id from ReadRequestPayload
	Found         bool                   `protobuf:"varint,3,opt,name=found,proto3" json:"found,omitempty"`
	ItemData      *StoredItem            `protobuf:"bytes,4,opt,name=item_data,json=itemData,proto3" json:"item_data,omitempty"` // Only present if found = true
	Version       int64                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	ResponderId   string                 `protobuf:"bytes,6,opt,name=responder_id,json=responderId,proto3" json:"responder_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponsePayload) Reset() {
	*x = ReadResponsePayload{}
	mi := &file_gridkv_gossip_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponsePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponsePayload) ProtoMessage() {}

func (x *ReadResponsePayload) ProtoReflect() protoreflect.Message {
	mi := &file_gridkv_gossip_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponsePayload.ProtoReflect.Descriptor instead.
func (*ReadResponsePayload) Descriptor() ([]byte, []int) {
	return file_gridkv_gossip_proto_rawDescGZIP(), []int{15}
}

func (x *ReadResponsePayload) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ReadResponsePayload) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ReadResponsePayload) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *ReadResponsePayload) GetItemData() *StoredItem {
	if x != nil {
		return x.ItemData
	}
	return nil
}

func (x *ReadResponsePayload) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ReadResponsePayload) GetResponderId() string {
	if x != nil {
		return x.ResponderId
	}
	return ""
}

// GossipMessage encapsulates the payload for transmission.
// NOTE: top-level fields 'signature', 'op_id', 'hlc' are placed here
// so they exist on every message without inflating each payload type.
type GossipMessage struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Type   GossipMessageType      `protobuf:"varint,1,opt,name=type,proto3,enum=gossip.GossipMessageType" json:"type,omitempty"`
	Sender string                 `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*GossipMessage_ConnectPayload
	//	*GossipMessage_ClusterSyncPayload
	//	*GossipMessage_ProbeRequestPayload
	//	*GossipMessage_ProbeResponsePayload
	//	*GossipMessage_CacheSyncPayload
	//	*GossipMessage_CacheSyncAckPayload
	//	*GossipMessage_FullSyncRequestPayload
	//	*GossipMessage_FullSyncResponsePayload
	//	*GossipMessage_ReadRequestPayload
	//	*GossipMessage_ReadResponsePayload
	Payload isGossipMessage_Payload `protobuf_oneof:"payload"`
	// Top-level metadata used by coordinator/replication and signing:
	// Op id used by coordinator when sending replication messages.
	OpId string `protobuf:"bytes,20,opt,name=op_id,json=opId,proto3" json:"op_id,omitempty"`
	// Optional HLC timestamp (format: node:unixnano:counter).
	Hlc string `protobuf:"bytes,21,opt,name=hlc,proto3" json:"hlc,omitempty"`
	// Signature of the canonicalized message bytes (see note below).
	Signature []byte `protobuf:"bytes,22,opt,name=signature,proto3" json:"signature,omitempty"`
	// Compression flag: if true, the payload is compressed with zstd
	Compressed    bool `protobuf:"varint,23,opt,name=compressed,proto3" json:"compressed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GossipMessage) Reset() {
	*x = GossipMessage{}
	mi := &file_gridkv_gossip_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GossipMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipMessage) ProtoMessage() {}

func (x *GossipMessage) ProtoReflect() protoreflect.Message {
	mi := &file_gridkv_gossip_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipMessage.ProtoReflect.Descriptor instead.
func (*GossipMessage) Descriptor() ([]byte, []int) {
	return file_gridkv_gossip_proto_rawDescGZIP(), []int{16}
}

func (x *GossipMessage) GetType() GossipMessageType {
	if x != nil {
		return x.Type
	}
	return GossipMessageType_MESSAGE_TYPE_UNKNOWN
}

func (x *GossipMessage) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *GossipMessage) GetPayload() isGossipMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GossipMessage) GetConnectPayload() *ConnectPayload {
	if x != nil {
		if x, ok := x.Payload.(*GossipMessage_ConnectPayload); ok {
			return x.ConnectPayload
		}
	}
	return nil
}

func (x *GossipMessage) GetClusterSyncPayload() *ClusterSyncPayload {
	if x != nil {
		if x, ok := x.Payload.(*GossipMessage_ClusterSyncPayload); ok {
			return x.ClusterSyncPayload
		}
	}
	return nil
}

func (x *GossipMessage) GetProbeRequestPayload() *ProbePayload {
	if x != nil {
		if x, ok := x.Payload.(*GossipMessage_ProbeRequestPayload); ok {
			return x.ProbeRequestPayload
		}
	}
	return nil
}

func (x *GossipMessage) GetProbeResponsePayload() *ProbeResponsePayload {
	if x != nil {
		if x, ok := x.Payload.(*GossipMessage_ProbeResponsePayload); ok {
			return x.ProbeResponsePayload
		}
	}
	return nil
}

func (x *GossipMessage) GetCacheSyncPayload() *SyncMessage {
	if x != nil {
		if x, ok := x.Payload.(*GossipMessage_CacheSyncPayload); ok {
			return x.CacheSyncPayload
		}
	}
	return nil
}

func (x *GossipMessage) GetCacheSyncAckPayload() *CacheSyncAckPayload {
	if x != nil {
		if x, ok := x.Payload.(*GossipMessage_CacheSyncAckPayload); ok {
			return x.CacheSyncAckPayload
		}
	}
	return nil
}

func (x *GossipMessage) GetFullSyncRequestPayload() *FullSyncRequestPayload {
	if x != nil {
		if x, ok := x.Payload.(*GossipMessage_FullSyncRequestPayload); ok {
			return x.FullSyncRequestPayload
		}
	}
	return nil
}

func (x *GossipMessage) GetFullSyncResponsePayload() *FullSyncResponsePayload {
	if x != nil {
		if x, ok := x.Payload.(*GossipMessage_FullSyncResponsePayload); ok {
			return x.FullSyncResponsePayload
		}
	}
	return nil
}

func (x *GossipMessage) GetReadRequestPayload() *ReadRequestPayload {
	if x != nil {
		if x, ok := x.Payload.(*GossipMessage_ReadRequestPayload); ok {
			return x.ReadRequestPayload
		}
	}
	return nil
}

func (x *GossipMessage) GetReadResponsePayload() *ReadResponsePayload {
	if x != nil {
		if x, ok := x.Payload.(*GossipMessage_ReadResponsePayload); ok {
			return x.ReadResponsePayload
		}
	}
	return nil
}

func (x *GossipMessage) GetOpId() string {
	if x != nil {
		return x.OpId
	}
	return ""
}

func (x *GossipMessage) GetHlc() string {
	if x != nil {
		return x.Hlc
	}
	return ""
}

func (x *GossipMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *GossipMessage) GetCompressed() bool {
	if x != nil {
		return x.Compressed
	}
	return false
}

type isGossipMessage_Payload interface {
	isGossipMessage_Payload()
}

type GossipMessage_ConnectPayload struct {
	ConnectPayload *ConnectPayload `protobuf:"bytes,3,opt,name=connect_payload,json=connectPayload,proto3,oneof"`
}

type GossipMessage_ClusterSyncPayload struct {
	ClusterSyncPayload *ClusterSyncPayload `protobuf:"bytes,4,opt,name=cluster_sync_payload,json=clusterSyncPayload,proto3,oneof"`
}

type GossipMessage_ProbeRequestPayload struct {
	ProbeRequestPayload *ProbePayload `protobuf:"bytes,5,opt,name=probe_request_payload,json=probeRequestPayload,proto3,oneof"`
}

type GossipMessage_ProbeResponsePayload struct {
	ProbeResponsePayload *ProbeResponsePayload `protobuf:"bytes,6,opt,name=probe_response_payload,json=probeResponsePayload,proto3,oneof"`
}

type GossipMessage_CacheSyncPayload struct {
	CacheSyncPayload *SyncMessage `protobuf:"bytes,7,opt,name=cache_sync_payload,json=cacheSyncPayload,proto3,oneof"`
}

type GossipMessage_CacheSyncAckPayload struct {
	CacheSyncAckPayload *CacheSyncAckPayload `protobuf:"bytes,8,opt,name=cache_sync_ack_payload,json=cacheSyncAckPayload,proto3,oneof"`
}

type GossipMessage_FullSyncRequestPayload struct {
	FullSyncRequestPayload *FullSyncRequestPayload `protobuf:"bytes,9,opt,name=full_sync_request_payload,json=fullSyncRequestPayload,proto3,oneof"`
}

type GossipMessage_FullSyncResponsePayload struct {
	FullSyncResponsePayload *FullSyncResponsePayload `protobuf:"bytes,10,opt,name=full_sync_response_payload,json=fullSyncResponsePayload,proto3,oneof"`
}

type GossipMessage_ReadRequestPayload struct {
	ReadRequestPayload *ReadRequestPayload `protobuf:"bytes,11,opt,name=read_request_payload,json=readRequestPayload,proto3,oneof"`
}

type GossipMessage_ReadResponsePayload struct {
	ReadResponsePayload *ReadResponsePayload `protobuf:"bytes,12,opt,name=read_response_payload,json=readResponsePayload,proto3,oneof"`
}

func (*GossipMessage_ConnectPayload) isGossipMessage_Payload() {}

func (*GossipMessage_ClusterSyncPayload) isGossipMessage_Payload() {}

func (*GossipMessage_ProbeRequestPayload) isGossipMessage_Payload() {}

func (*GossipMessage_ProbeResponsePayload) isGossipMessage_Payload() {}

func (*GossipMessage_CacheSyncPayload) isGossipMessage_Payload() {}

func (*GossipMessage_CacheSyncAckPayload) isGossipMessage_Payload() {}

func (*GossipMessage_FullSyncRequestPayload) isGossipMessage_Payload() {}

func (*GossipMessage_FullSyncResponsePayload) isGossipMessage_Payload() {}

func (*GossipMessage_ReadRequestPayload) isGossipMessage_Payload() {}

func (*GossipMessage_ReadResponsePayload) isGossipMessage_Payload() {}

var File_gridkv_gossip_proto protoreflect.FileDescriptor

const file_gridkv_gossip_proto_rawDesc = "" +
	"\n" +
	"\x13gridkv_gossip.proto\x12\x06gossip\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc2\x01\n" +
	"\bNodeInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12@\n" +
	"\x0elast_active_ts\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\flastActiveTs\x12'\n" +
	"\x05state\x18\x04 \x01(\x0e2\x11.gossip.NodeStateR\x05state\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x03R\aversion\"\x8e\x01\n" +
	"\x0eConnectPayload\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\x12\x10\n" +
	"\x03hlc\x18\x04 \x01(\tR\x03hlc\x12\x1d\n" +
	"\n" +
	"public_key\x18\x05 \x01(\fR\tpublicKey\"<\n" +
	"\x12ClusterSyncPayload\x12&\n" +
	"\x05nodes\x18\x01 \x03(\v2\x10.gossip.NodeInfoR\x05nodes\"W\n" +
	"\fProbePayload\x12$\n" +
	"\x0etarget_node_id\x18\x01 \x01(\tR\ftargetNodeId\x12!\n" +
	"\frequester_id\x18\x02 \x01(\tR\vrequesterId\"R\n" +
	"\x14ProbeResponsePayload\x12$\n" +
	"\x0etarget_node_id\x18\x01 \x01(\tR\ftargetNodeId\x12\x14\n" +
	"\x05alive\x18\x02 \x01(\bR\x05alive\"?\n" +
	"\n" +
	"StoredItem\x12\x1b\n" +
	"\texpire_at\x18\x01 \x01(\x06R\bexpireAt\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"\xb9\x01\n" +
	"\x12CacheSyncOperation\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x0eclient_version\x18\x02 \x01(\x03R\rclientVersion\x12)\n" +
	"\x04type\x18\x03 \x01(\x0e2\x15.gossip.OperationTypeR\x04type\x12/\n" +
	"\bset_data\x18\x04 \x01(\v2\x12.gossip.StoredItemH\x00R\asetDataB\x0e\n" +
	"\fdata_payload\"s\n" +
	"\x16IncrementalSyncPayload\x12:\n" +
	"\n" +
	"operations\x18\x01 \x03(\v2\x1a.gossip.CacheSyncOperationR\n" +
	"operations\x12\x1d\n" +
	"\n" +
	"payload_id\x18\x02 \x01(\tR\tpayloadId\"l\n" +
	"\rFullStateItem\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12/\n" +
	"\titem_data\x18\x03 \x01(\v2\x12.gossip.StoredItemR\bitemData\"m\n" +
	"\x0fFullSyncPayload\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.gossip.FullStateItemR\x05items\x12-\n" +
	"\x12snapshot_timestamp\x18\x02 \x01(\x06R\x11snapshotTimestamp\"\x9f\x01\n" +
	"\vSyncMessage\x12K\n" +
	"\x10incremental_sync\x18\x01 \x01(\v2\x1e.gossip.IncrementalSyncPayloadH\x00R\x0fincrementalSync\x126\n" +
	"\tfull_sync\x18\x02 \x01(\v2\x17.gossip.FullSyncPayloadH\x00R\bfullSyncB\v\n" +
	"\tsync_type\"]\n" +
	"\x13CacheSyncAckPayload\x12\x13\n" +
	"\x05op_id\x18\x01 \x01(\tR\x04opId\x12\x17\n" +
	"\apeer_id\x18\x02 \x01(\tR\x06peerId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\";\n" +
	"\x16FullSyncRequestPayload\x12!\n" +
	"\frequester_id\x18\x01 \x01(\tR\vrequesterId\"O\n" +
	"\x17FullSyncResponsePayload\x124\n" +
	"\tfull_sync\x18\x01 \x01(\v2\x17.gossip.FullSyncPayloadR\bfullSync\"h\n" +
	"\x12ReadRequestPayload\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12!\n" +
	"\frequester_id\x18\x02 \x01(\tR\vrequesterId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\"\xca\x01\n" +
	"\x13ReadResponsePayload\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x14\n" +
	"\x05found\x18\x03 \x01(\bR\x05found\x12/\n" +
	"\titem_data\x18\x04 \x01(\v2\x12.gossip.StoredItemR\bitemData\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x03R\aversion\x12!\n" +
	"\fresponder_id\x18\x06 \x01(\tR\vresponderId\"\xf4\a\n" +
	"\rGossipMessage\x12-\n" +
	"\x04type\x18\x01 \x01(\x0e2\x19.gossip.GossipMessageTypeR\x04type\x12\x16\n" +
	"\x06sender\x18\x02 \x01(\tR\x06sender\x12A\n" +
	"\x0fconnect_payload\x18\x03 \x01(\v2\x16.gossip.ConnectPayloadH\x00R\x0econnectPayload\x12N\n" +
	"\x14cluster_sync_payload\x18\x04 \x01(\v2\x1a.gossip.ClusterSyncPayloadH\x00R\x12clusterSyncPayload\x12J\n" +
	"\x15probe_request_payload\x18\x05 \x01(\v2\x14.gossip.ProbePayloadH\x00R\x13probeRequestPayload\x12T\n" +
	"\x16probe_response_payload\x18\x06 \x01(\v2\x1c.gossip.ProbeResponsePayloadH\x00R\x14probeResponsePayload\x12C\n" +
	"\x12cache_sync_payload\x18\a \x01(\v2\x13.gossip.SyncMessageH\x00R\x10cacheSyncPayload\x12R\n" +
	"\x16cache_sync_ack_payload\x18\b \x01(\v2\x1b.gossip.CacheSyncAckPayloadH\x00R\x13cacheSyncAckPayload\x12[\n" +
	"\x19full_sync_request_payload\x18\t \x01(\v2\x1e.gossip.FullSyncRequestPayloadH\x00R\x16fullSyncRequestPayload\x12^\n" +
	"\x1afull_sync_response_payload\x18\n" +
	" \x01(\v2\x1f.gossip.FullSyncResponsePayloadH\x00R\x17fullSyncResponsePayload\x12N\n" +
	"\x14read_request_payload\x18\v \x01(\v2\x1a.gossip.ReadRequestPayloadH\x00R\x12readRequestPayload\x12Q\n" +
	"\x15read_response_payload\x18\f \x01(\v2\x1b.gossip.ReadResponsePayloadH\x00R\x13readResponsePayload\x12\x13\n" +
	"\x05op_id\x18\x14 \x01(\tR\x04opId\x12\x10\n" +
	"\x03hlc\x18\x15 \x01(\tR\x03hlc\x12\x1c\n" +
	"\tsignature\x18\x16 \x01(\fR\tsignature\x12\x1e\n" +
	"\n" +
	"compressed\x18\x17 \x01(\bR\n" +
	"compressedB\t\n" +
	"\apayload*f\n" +
	"\tNodeState\x12\x16\n" +
	"\x12NODE_STATE_UNKNOWN\x10\x00\x12\x14\n" +
	"\x10NODE_STATE_ALIVE\x10\x01\x12\x16\n" +
	"\x12NODE_STATE_SUSPECT\x10\x02\x12\x13\n" +
	"\x0fNODE_STATE_DEAD\x10\x03*\xed\x02\n" +
	"\x11GossipMessageType\x12\x18\n" +
	"\x14MESSAGE_TYPE_UNKNOWN\x10\x00\x12\x1b\n" +
	"\x17MESSAGE_TYPE_CACHE_SYNC\x10\x01\x12\x1d\n" +
	"\x19MESSAGE_TYPE_CLUSTER_SYNC\x10\x02\x12\x18\n" +
	"\x14MESSAGE_TYPE_CONNECT\x10\x03\x12\x1e\n" +
	"\x1aMESSAGE_TYPE_PROBE_REQUEST\x10\x04\x12\x1f\n" +
	"\x1bMESSAGE_TYPE_PROBE_RESPONSE\x10\x05\x12\x1f\n" +
	"\x1bMESSAGE_TYPE_CACHE_SYNC_ACK\x10\x06\x12\"\n" +
	"\x1eMESSAGE_TYPE_FULL_SYNC_REQUEST\x10\a\x12#\n" +
	"\x1fMESSAGE_TYPE_FULL_SYNC_RESPONSE\x10\b\x12\x1d\n" +
	"\x19MESSAGE_TYPE_READ_REQUEST\x10\t\x12\x1e\n" +
	"\x1aMESSAGE_TYPE_READ_RESPONSE\x10\n" +
	"*>\n" +
	"\rOperationType\x12\x12\n" +
	"\x0eOP_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06OP_SET\x10\x01\x12\r\n" +
	"\tOP_DELETE\x10\x02B\x18Z\x16internal/gossip;gossipb\x06proto3"

var (
	file_gridkv_gossip_proto_rawDescOnce sync.Once
	file_gridkv_gossip_proto_rawDescData []byte
)

func file_gridkv_gossip_proto_rawDescGZIP() []byte {
	file_gridkv_gossip_proto_rawDescOnce.Do(func() {
		file_gridkv_gossip_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gridkv_gossip_proto_rawDesc), len(file_gridkv_gossip_proto_rawDesc)))
	})
	return file_gridkv_gossip_proto_rawDescData
}

var file_gridkv_gossip_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_gridkv_gossip_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_gridkv_gossip_proto_goTypes = []any{
	(NodeState)(0),                  // 0: gossip.NodeState
	(GossipMessageType)(0),          // 1: gossip.GossipMessageType
	(OperationType)(0),              // 2: gossip.OperationType
	(*NodeInfo)(nil),                // 3: gossip.NodeInfo
	(*ConnectPayload)(nil),          // 4: gossip.ConnectPayload
	(*ClusterSyncPayload)(nil),      // 5: gossip.ClusterSyncPayload
	(*ProbePayload)(nil),            // 6: gossip.ProbePayload
	(*ProbeResponsePayload)(nil),    // 7: gossip.ProbeResponsePayload
	(*StoredItem)(nil),              // 8: gossip.StoredItem
	(*CacheSyncOperation)(nil),      // 9: gossip.CacheSyncOperation
	(*IncrementalSyncPayload)(nil),  // 10: gossip.IncrementalSyncPayload
	(*FullStateItem)(nil),           // 11: gossip.FullStateItem
	(*FullSyncPayload)(nil),         // 12: gossip.FullSyncPayload
	(*SyncMessage)(nil),             // 13: gossip.SyncMessage
	(*CacheSyncAckPayload)(nil),     // 14: gossip.CacheSyncAckPayload
	(*FullSyncRequestPayload)(nil),  // 15: gossip.FullSyncRequestPayload
	(*FullSyncResponsePayload)(nil), // 16: gossip.FullSyncResponsePayload
	(*ReadRequestPayload)(nil),      // 17: gossip.ReadRequestPayload
	(*ReadResponsePayload)(nil),     // 18: gossip.ReadResponsePayload
	(*GossipMessage)(nil),           // 19: gossip.GossipMessage
	(*timestamppb.Timestamp)(nil),   // 20: google.protobuf.Timestamp
}
var file_gridkv_gossip_proto_depIdxs = []int32{
	20, // 0: gossip.NodeInfo.last_active_ts:type_name -> google.protobuf.Timestamp
	0,  // 1: gossip.NodeInfo.state:type_name -> gossip.NodeState
	3,  // 2: gossip.ClusterSyncPayload.nodes:type_name -> gossip.NodeInfo
	2,  // 3: gossip.CacheSyncOperation.type:type_name -> gossip.OperationType
	8,  // 4: gossip.CacheSyncOperation.set_data:type_name -> gossip.StoredItem
	9,  // 5: gossip.IncrementalSyncPayload.operations:type_name -> gossip.CacheSyncOperation
	8,  // 6: gossip.FullStateItem.item_data:type_name -> gossip.StoredItem
	11, // 7: gossip.FullSyncPayload.items:type_name -> gossip.FullStateItem
	10, // 8: gossip.SyncMessage.incremental_sync:type_name -> gossip.IncrementalSyncPayload
	12, // 9: gossip.SyncMessage.full_sync:type_name -> gossip.FullSyncPayload
	12, // 10: gossip.FullSyncResponsePayload.full_sync:type_name -> gossip.FullSyncPayload
	8,  // 11: gossip.ReadResponsePayload.item_data:type_name -> gossip.StoredItem
	1,  // 12: gossip.GossipMessage.type:type_name -> gossip.GossipMessageType
	4,  // 13: gossip.GossipMessage.connect_payload:type_name -> gossip.ConnectPayload
	5,  // 14: gossip.GossipMessage.cluster_sync_payload:type_name -> gossip.ClusterSyncPayload
	6,  // 15: gossip.GossipMessage.probe_request_payload:type_name -> gossip.ProbePayload
	7,  // 16: gossip.GossipMessage.probe_response_payload:type_name -> gossip.ProbeResponsePayload
	13, // 17: gossip.GossipMessage.cache_sync_payload:type_name -> gossip.SyncMessage
	14, // 18: gossip.GossipMessage.cache_sync_ack_payload:type_name -> gossip.CacheSyncAckPayload
	15, // 19: gossip.GossipMessage.full_sync_request_payload:type_name -> gossip.FullSyncRequestPayload
	16, // 20: gossip.GossipMessage.full_sync_response_payload:type_name -> gossip.FullSyncResponsePayload
	17, // 21: gossip.GossipMessage.read_request_payload:type_name -> gossip.ReadRequestPayload
	18, // 22: gossip.GossipMessage.read_response_payload:type_name -> gossip.ReadResponsePayload
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_gridkv_gossip_proto_init() }
func file_gridkv_gossip_proto_init() {
	if File_gridkv_gossip_proto != nil {
		return
	}
	file_gridkv_gossip_proto_msgTypes[6].OneofWrappers = []any{
		(*CacheSyncOperation_SetData)(nil),
	}
	file_gridkv_gossip_proto_msgTypes[10].OneofWrappers = []any{
		(*SyncMessage_IncrementalSync)(nil),
		(*SyncMessage_FullSync)(nil),
	}
	file_gridkv_gossip_proto_msgTypes[16].OneofWrappers = []any{
		(*GossipMessage_ConnectPayload)(nil),
		(*GossipMessage_ClusterSyncPayload)(nil),
		(*GossipMessage_ProbeRequestPayload)(nil),
		(*GossipMessage_ProbeResponsePayload)(nil),
		(*GossipMessage_CacheSyncPayload)(nil),
		(*GossipMessage_CacheSyncAckPayload)(nil),
		(*GossipMessage_FullSyncRequestPayload)(nil),
		(*GossipMessage_FullSyncResponsePayload)(nil),
		(*GossipMessage_ReadRequestPayload)(nil),
		(*GossipMessage_ReadResponsePayload)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gridkv_gossip_proto_rawDesc), len(file_gridkv_gossip_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gridkv_gossip_proto_goTypes,
		DependencyIndexes: file_gridkv_gossip_proto_depIdxs,
		EnumInfos:         file_gridkv_gossip_proto_enumTypes,
		MessageInfos:      file_gridkv_gossip_proto_msgTypes,
	}.Build()
	File_gridkv_gossip_proto = out.File
	file_gridkv_gossip_proto_goTypes = nil
	file_gridkv_gossip_proto_depIdxs = nil
}
